services:
  learning_base:
    build: .
    image: energy_predictor/learningbase:latest
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/learningBase/ && cp -r ../learningBase/ /tmp/;
volumes:
  ai_system:
    external: true