services:
  learning_base:
    build: .
    image: anteab/learningbase_energy_prediction
    container_name: learningbase_energy_prediction
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/learningBase/ && cp -r ../learningBase/ /tmp/ && tail -f /dev/null;
volumes:
  ai_system:
    external: true