services:
  activation_base:
    build: .
    image: energy_predictor/activationbase:latest
    container_name: energy_predictor_activationbase
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/activationBase/ && cp -r ../activationBase/ /tmp/;
volumes:
  ai_system:
    external: true