services:
  activation_base:
    build: .
    image: anteab/activationbase_energy_prediction:latest
    container_name: activationbase_energy_prediction
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/activationBase/ && cp -r ../activationBase/ /tmp/;
volumes:
  ai_system:
    external: true