services:
  activation_base:
    build: .
    image: anteab/knowledgebase_energy_prediction:latest
    container_name: knowledgebase_energy_prediction
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/knowledgeBase/ && cp -r ../knowledgeBase/ /tmp/;
volumes:
  ai_system:
    external: true